### ISSUE TITLE
Photo Card Grid

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#10]
The example card grid features a series of cards consisting of:

1. Location
2. A picture representing the example
3. The title/name of the example
4. Related tags (up to 3) (TBD: Confirm)
5. A short description (not depicted)

No more than 4 examples may be placed in a row

Grid should scale as: 1, 2, 4

![screenshot 2018-02-28 16 57 56](https://user-images.githubusercontent.com/84750/36815403-94f51e62-1ca8-11e8-8c7a-c30705180427.png)

**Comment by mtrythall** [comment]
Passed to @sodevious since she's building this elsewhere.

**Comment by sodevious** [comment]
<img width="323" alt="screenshot 2018-04-09 15 01 42" src="https://user-images.githubusercontent.com/915966/38517133-f3283618-3c06-11e8-9f27-17bf89982988.png">
