### ISSUE TITLE
Icon Card

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#13]
An icon card consists of:

1. A title
2. Short (rich) text (optional)
3. An icon
4. Optional set of classes (TBD) (optional)

These may be added to multiple components.

![screenshot 2018-02-28 17 12 53](https://user-images.githubusercontent.com/84750/36816020-9f8589b4-1caa-11e8-8aa1-486a2d204e99.png)

![screenshot 2018-02-28 17 13 12](https://user-images.githubusercontent.com/84750/36816043-aaa352ea-1caa-11e8-8812-18c987446a79.png)

**Comment by mtrythall** [comment]
@nicolaslara Probably good to allow an icon to be uploaded or selected from a system similar to those on other projects.

**Comment by nicolaslara** [comment]
I'm keeping the icons as images selected from filer for now. We need to discuss how to deal with static icons as this beings some complexities.

**Comment by mtrythall** [comment]
@nicolaslara I think that might be a problem if we want to use SVG icons, which I do not think filer supports.

<img width="538" alt="screenshot 2018-03-17 13 21 53" src="https://user-images.githubusercontent.com/84750/37558161-3086b378-29e6-11e8-8827-097ff08af2e1.png">

Any icon pack we use is going to be SVG and rightfully so as we may need to theme these. How do you want to handle?

**Comment by nicolaslara** [comment]
That error was on old code. This should work now.

**Comment by mtrythall** [comment]
We need the minimal icon style here, as depicted first in the image above.

**Comment by mtrythall** [comment]
To clarify, we want the layout of the *second* version above (text is full width), but we want the icon in a box.

**Comment by sodevious** [comment]
In [styleguide](http://localhost:8000/static/styleguide/section-components.html#kssref-components-card)
<img width="517" alt="screenshot 2018-03-28 15 44 04" src="https://user-images.githubusercontent.com/915966/38052376-125b70b6-329f-11e8-90da-04d92575713e.png">

**Comment by sodevious** [comment]
@mtrythall @nicolaslara I think the backend for this should allow for styles to be passed, just like the Block model.

ie `default`, `light`,`dark`

**Comment by sodevious** [comment]
@mtrythall oh that makes sense!

**Comment by mtrythall** [comment]
Moving back to in progress since we need to adjust how themes work a little and make linking work better.
