### ISSUE TITLE
Section Component

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#14]
The Section component features the following:

1. Title
2. Image (optional)
3. Rich text (optional)
4. A call to action button (link, optional)

Sections can accept any of the following:

1. An image
2. Icon Card
3. Map
4. Text

![screenshot 2018-02-28 17 23 18](https://user-images.githubusercontent.com/84750/36816540-140c0b22-1cac-11e8-9ec9-64786f678a8f.png)

**Comment by nicolaslara** [comment]
We are splitting the section plugin in "Section + Cards" and "Section + Text".

Besides clarity, the main technical difference is what I describe in https://github.com/rapidpro/chpro-microsite/issues/12#issuecomment-372630539. Section+Text allows for very rich text editing, so no child plugins are allowed. Section+Cards limits the text to the standard WYSIWYG but allows cards.

**Comment by mtrythall** [comment]
@nicolaslara Is the intent that the image is added via the WYSIWYG editor or via a separate field?

I vote separate field. Adding it via the WYSIWYG seems to be a poor experience for the editor currently (too many popups, can't access the save button on a small display).

**Comment by mtrythall** [comment]
This needs:

1. An image field (on the section itself, not a child)
2. A style (drop down) option that will determine the background color

I'll split out sub-components.

**Comment by mtrythall** [comment]
@SmileyChris Could you add the image here please?

**Comment by mtrythall** [comment]
@SmileyChris Also, we need to figure out this part:

Sections can accept any of the following:

An image
Icon Card
Map
Text

Nicolas was hitting an issue with plugins between the WYSIWYG and those that were added. Links get added as a plugin, so we'd end up with plugins we didn't want as children. It'd be nice to address that some how, but can maybe wait until he's back.

**Comment by SmileyChris** [comment]
Now the plugins can be removed from the wsywig option if necessary. Embedded plugins won't be double-rendered now either.

I've merged the section plugin to a single one now. You can add a card grid, not individual cards.

There's a new RawHTML plugin instead of a specific "map" one.
