### ISSUE TITLE
Setup the build system with another entry point for the admin

### ISSUE THREAD

**Issue by nicolaslara** [rapidpro/chpro-microsite#16]
This should support the admin's default jquery and plugins like select2

**Comment by mtrythall** [comment]
@nicolaslara Can you clarify this one? Do we need it for so few files?

**Comment by nicolaslara** [comment]
I experimented on this with Marco but it didn't work as expected. We should be able to improve on it with https://github.com/parcel-bundler/parcel/pull/1119. However, we won't be able to load all the admin js via parcel because of the way select2 attaches itself to jquery (and the presence of several jquery versions due to django cms).

In short, we can close this.
