### ISSUE TITLE
Header should not show Homepage link

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#18]
The menu code we're using from Django CMS is showing the Homepage. This should not appear. The navigation should start at "About"

**Comment by mtrythall** [comment]
I can hide this with CSS, but that feels wrong given the duplication in nav items in the HTML. Ideally, navigation does not include the homepage.

Should we solve this in the templates? Happy to pitch in, just want to know the *right* way to solve it.

**Comment by mtrythall** [comment]
Note, we want the homepage to appear in *other* menus, just not the one in the header on desktop.

**Comment by nicolaslara** [comment]
That's because I designed it with a different page structure in mind. I've fixed it on the test server and reverted the menu values to match. 

<img width="250" alt="list_of_pages" src="https://user-images.githubusercontent.com/37868/37698453-54438566-2ce3-11e8-9c38-776ff2bfdb2c.png">

**Comment by mtrythall** [comment]
Ok, I figured as much, but thought I'd check. Thanks!
