### ISSUE TITLE
Step Detail Plugin

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#20]
Name WIP

Step detail plugin features the following:

1. An icon
2. Title
3. Text (WYSIWYG)
4. Files (under Tools)
5. Related Links (under Examples)

Not sure how you want to handle 4 and 5 @nicolaslara 

![screenshot 2018-03-21 12 10 51](https://user-images.githubusercontent.com/84750/37721830-e8b59eb0-2d00-11e8-814c-c2155d8f2c38.png)

**Comment by sodevious** [comment]
Could it be "Step (complex)" akin to Hero/Hero (complex)?

**Comment by sodevious** [comment]
Should these icons be white to match the white numbers in the regular Step plugin?

![37720223-35884dea-2cfd-11e8-8fa0-6b1ae07883da](https://user-images.githubusercontent.com/915966/38041511-eb7f62d2-327f-11e8-870d-9e3112fb2537.png)
![37721830-e8b59eb0-2d00-11e8-814c-c2155d8f2c38](https://user-images.githubusercontent.com/915966/38041513-ec5bb1a6-327f-11e8-9d8f-90955fde19ef.png)

**Comment by mtrythall** [comment]
@sodevious Sure, make 'em white.

**Comment by mtrythall** [comment]
@sodevious can you plug this into the CMS? We should have plugins for them now. Take a stab at it please :-)

**Comment by sodevious** [comment]
@SmileyChris Can you please allow the Step model/plugin to take an svg icon?
<img width="902" alt="screenshot 2018-04-04 14 28 34" src="https://user-images.githubusercontent.com/915966/38326715-7cd06468-3814-11e8-9344-9e33ba7eb44f.png">

**Comment by mtrythall** [comment]
I'm not seeing duplication here, I think we're good. LMK if you're still seeing this @sodevious 

@SmileyChris Can you add the SVG icon field to this model please?

**Comment by SmileyChris** [comment]
@mtrythall you want the svg icon field displayed after body?

**Comment by mtrythall** [comment]
SVG icon field should be displayed before body. I believe it's high up
everywhere else.

**Comment by sodevious** [comment]
@SmileyChris  StepFiles should have a field for "Link Text"

<img width="834" alt="screenshot 2018-04-09 12 16 42" src="https://user-images.githubusercontent.com/915966/38509448-e6561d7c-3bef-11e8-9884-05425c274b0e.png">
<img width="274" alt="screenshot 2018-04-09 12 17 06" src="https://user-images.githubusercontent.com/915966/38509460-ec129a88-3bef-11e8-9a92-a832d3f6cb96.png">
