### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#21]

**Comment by nicolaslara** [comment]
The backend for this is in. Needs design.

**Comment by mtrythall** [comment]
Only thing missing here is fleshing out the sidebar.

**Comment by mtrythall** [comment]
This just needs design clean up and I need to see related case studies at the bottom work.

**Comment by mtrythall** [comment]
This needs a second set of eyes. I don't think there is much to it, and portions of it are blocked by #40, but by golly, I'm sure I missed something.

**Comment by sodevious** [comment]
<img width="727" alt="screenshot 2018-04-24 16 30 57" src="https://user-images.githubusercontent.com/915966/39212530-fd32db36-47dc-11e8-87e7-cca65b534a85.png">
