### ISSUE TITLE
Back to Top Link on Heroes

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#22]
The top of heroes occasionally needs a "Back to <parent>" link

![screenshot 2018-03-21 12 47 46](https://user-images.githubusercontent.com/84750/37723979-1f63ae52-2d06-11e8-9c9b-af4c0e6ec5af.png)

**Comment by mtrythall** [comment]
@nicolaslara Not sure how to handle this one yet. Maybe we can make it an option or we can add a link to Hero (Complex) like we do for Section?

**Comment by nicolaslara** [comment]
I thought that would just be a link to the parent page. I added the variable on the content template, we should be able to style it to float above the first plugin in the header placeholder
