### ISSUE TITLE
Function/Use Case Detail View

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#24]
This view features a Hero element with an icon. Beneath this are 2 columns (on desktop), featuring an image and WYSIWYG area (or series of plugins).

Prototype: https://projects.invisionapp.com/d/#/console/13644598/285078903/preview

**Comment by nicolaslara** [comment]
Added this. We would handle these pages by using a "Content template" instead of the default "Generic template". Needs html/css.

**Comment by mtrythall** [comment]
Closing this out. You can build the layout. Individual items have design quirks, will handle them elsewhere.
