### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#25]
Because of how this is designed, with all the content being in the box, we probably need this to be its own plugin.

It should take:

1. Quote text
2. Quote author
3. Quote author title

It's possible to solve some of this with styles in the WYSIWYG too, perhaps, or to add it as a plugin in the WYSIWYG component itself. Deferring to @nicolaslara 

<img width="697" alt="screenshot 2018-03-21 15 41 29" src="https://user-images.githubusercontent.com/84750/37733421-5e3ffdc0-2d1e-11e8-8b2e-30a237b660b9.png">

**Comment by mtrythall** [comment]
@sodevious Can you tackle this? I just need the markup, CSS, etc. No Django side yet AFAIK. Document it in the styleguide, please.

**Comment by sodevious** [comment]
@mtrythall Once you rebuild the styleguide, this will be available here: http://localhost:8000/static/styleguide/section-components.html#kssref-components-blockquote

**Comment by mtrythall** [comment]
This should just need backend. Passing to @nicolaslara

**Comment by mtrythall** [comment]
Please pass to @sodevious when the backend is in place, please.
