### ISSUE TITLE
Case Study List

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#26]
<img width="1055" alt="screenshot 2018-03-21 16 07 55" src="https://user-images.githubusercontent.com/84750/37734629-23a78562-2d22-11e8-93b1-5a8119f4c0ad.png">

This is found at the bottom of Case Studies. It does not need to be a reusable style. We just need to support the HTML/CSS for it and create the background theme.

**Comment by mtrythall** [comment]
I have a *rough* version of photo cards (called image cards currently) in the system. I'm trying to flesh that out today, but you can use that HTML for this.

**Comment by sodevious** [comment]
_Backend note:_ I did the markup for this on https://github.com/rapidpro/chpro-microsite/blob/14fa0fdd38694190d3fc3421af7ab0d4cec9991f/rh/templates/case_studies/case_study_list.html `case_study_list.html`, but it technically should live on `case_study.html`. The backend for that isn't supported yet. Seems like it should render possibly 4 random case studies from the tag that the current case study uses, ie `Immunisation`.

**Comment by SmileyChris** [comment]
So the backend logic is to add up to four totally random case studies (excluding the current one)?

**Comment by mtrythall** [comment]
Random based on similar tags, but always show four. If you don't have four with those tags, grab something else.

**Comment by sodevious** [comment]
<img width="1250" alt="screenshot 2018-03-28 15 44 47" src="https://user-images.githubusercontent.com/915966/38052442-48376b2c-329f-11e8-8385-cf888fd86179.png">

**Comment by mtrythall** [comment]
@SmileyChris Can you pull this into the case study detail page please? Then we can close it out.
