### ISSUE TITLE
Add prefixing to SCSS

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#28]
We're not currently prefixing. Pete said that we can just add browserlist to package.json and Parcel will handle if we're using PostCSS.

We need to try this.

We need to work against this browser matrix:

<img width="732" alt="screenshot 2018-03-21 22 24 20" src="https://user-images.githubusercontent.com/84750/37747643-9ccf112e-2d56-11e8-95f4-0b5b62462eb4.png">

<img width="743" alt="screenshot 2018-03-21 22 24 32" src="https://user-images.githubusercontent.com/84750/37747650-a48f9780-2d56-11e8-847e-b66dd3e79b41.png">

**Comment by mtrythall** [comment]
@sodevious Can you tackle this one? Not sure if you've worked with Parcel, but we're giving it a shot on the project: https://parceljs.org/

You can see some docs on how to do this here: https://parceljs.org/transforms.html#postcss

Posting to our #feux-war-room channel is good if you have questions. The LL team is very interested in this.

**Comment by sodevious** [comment]
Some examples of the new auto prefixing 

<img width="402" alt="screenshot 2018-03-30 17 20 43" src="https://user-images.githubusercontent.com/915966/38154583-b56836ca-3440-11e8-9ca6-f4cc1f93e349.png">
<img width="373" alt="screenshot 2018-03-30 17 20 52" src="https://user-images.githubusercontent.com/915966/38154584-b578236e-3440-11e8-9ba0-0cb1c0e5729d.png">
