### ISSUE TITLE
Case Study Filter

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#29]
The case study filter allows the user to filter case studies by tag.

<img width="1040" alt="screenshot 2018-03-22 09 33 26" src="https://user-images.githubusercontent.com/84750/37773465-15733242-2db4-11e8-8dba-49cd9e2eb664.png">

**Comment by mtrythall** [comment]
This is added as an Application via Django CMS. You can preview it here:

https://unicef-rapidpro-for-health.herokuapp.com/case-studies/

Logged in, click Advanced Settings.

@SmileyChris This needs a backend. There is currently no way to filter. Ideally this works in a way that produces a URL they can share. We'll have more filters later.

**Comment by SmileyChris** [comment]
Alright, try this out... 
I've left the tags in there, just ignore those and set one or more case studies. You should be able to use the filter options on the case studies page to filter by use cases.

**Comment by sodevious** [comment]
Should the URL be the slug of the filter?

Current `http://localhost:8000/case-studies/?filter=5`
Proposed `http://localhost:8000/case-studies/?filter=family-planning`

**Comment by mtrythall** [comment]
^^ Chris I'm voting slug. What do you think?

**Comment by mtrythall** [comment]
Also, the client requested late today to have region be a filterable option. @SmileyChris is this something we can do?

**Comment by sodevious** [comment]
@SmileyChris How do we use `{{ case.use_cases }}`?

This is what I'm getting even though I have something selected on the case study.
<img width="480" alt="screenshot 2018-04-06 18 30 56" src="https://user-images.githubusercontent.com/915966/38447127-a70887d6-39c9-11e8-949d-cbbd7963eeb9.png">
<img width="280" alt="screenshot 2018-04-06 18 37 31" src="https://user-images.githubusercontent.com/915966/38447128-a735912c-39c9-11e8-8e96-984396d27905.png">

**Comment by SmileyChris** [comment]
`use_cases` is a queryset. You can iterate it with {% for case.use_cases.all %}
An individual case is an `Page` model of which you can use `get_title`, `get_slug`, `get_absolute_url` and `metaattributes.svg_icon`

**Comment by sodevious** [comment]
@SmileyChris thanks! having trouble with the admin for this now. 

1. Create a case study
<img width="981" alt="screenshot 2018-04-09 11 44 03" src="https://user-images.githubusercontent.com/915966/38507855-a8334212-3beb-11e8-81d4-ccb659638a26.png">


2. Add a page using the + under "Case Studies"
<img width="619" alt="screenshot 2018-04-09 11 44 14" src="https://user-images.githubusercontent.com/915966/38507848-a222b56a-3beb-11e8-96c6-457a968a9b7d.png">


3. Page appears initially. On "Save" of the case study, it throws an error and the page list disappears.
<img width="893" alt="screenshot 2018-04-09 11 44 41" src="https://user-images.githubusercontent.com/915966/38507838-9b916688-3beb-11e8-9d5d-2e024c645a2a.png">

**Comment by sodevious** [comment]
@SmileyChris realize now this piece is still under development. sorry about that!

**Comment by mtrythall** [comment]
@sodevious I'm OK with the list of checkboxes for now. Can you clean up the list on the left here, add some sub-labels, and make the UI work better on mobile please (maybe use a Foundation accordion)?

**Comment by mtrythall** [comment]
@sodevious You'll need to add pages under Use Cases to get them to appear under Case Studies>Use Cases on the Case Study model. Check the staging site.

**Comment by mtrythall** [comment]
Also, still missing use cases. Have to look at it tomorrow with you.

**Comment by SmileyChris** [comment]
So to be clear: only published use cases will be shown under the use case list.

**Comment by mtrythall** [comment]
Referring to use cases as tags on cards. Sorry for confusion

**Comment by mtrythall** [comment]
This is looking really great @sodevious ! More detail tomorrow/Thursday, but so far so good!

**Comment by mtrythall** [comment]
I think this works. Let's wait for client feedback. Closing for now.
