### ISSUE TITLE
Nav disappears on case study pages

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#32]
There is no nav on case study pages: https://unicef-rapidpro-for-health.herokuapp.com/case-studies/help-for-chad/

**Comment by SmileyChris** [comment]
I think this is just a rendering bug? I saw it once, but hit refresh and nav is fine again and can't reproduce now.

**Comment by mtrythall** [comment]
No, don't think so. Screenshot of the DOM from Google Dev Tools attached.

<img width="409" alt="screenshot 2018-03-27 23 12 30" src="https://user-images.githubusercontent.com/84750/38006787-6d70b78a-3214-11e8-90da-5368456f1b1c.png">

This is a Case Study, which is a Django model, and I believe has a Django CMS page associated with it. I don't think Django CMS is available in the context, so menu tags, and those specific to tree traversal, work.

I could be wrong, but the DOM being blank is a giveaway. The off canvas nav (just a bit higher in the DOM, see it by shrinking down the browser on other pages) is empty too. Also, the back link is hardcoded, which is why it works.

**Comment by SmileyChris** [comment]
Ok, I see it now -- it's specifically when in "edit" mode for that page. 

It turns out that django-cms always decides to use the published node as the current node, even when that page is being edited.
