### ISSUE TITLE
Sections should allow for themes

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#35]
We need to support yellow, beige, and white (default)

<img width="1058" alt="screenshot 2018-03-27 10 13 21" src="https://user-images.githubusercontent.com/84750/37972982-7c57e100-31a7-11e8-9ff9-14738c8517d8.png">

**Comment by mtrythall** [comment]
Don't sweat adding this to the model yet, just the styles.

**Comment by mtrythall** [comment]
We need:

White (default)
Light (Yellow color)
Dark (Beige color)

**Comment by mtrythall** [comment]
@SmileyChris Can you add these to the Section component?

**Comment by SmileyChris** [comment]
@mtrythall added the style to the component, but haven't changed any template code to use this new `style` attribute...

**Comment by sodevious** [comment]
@SmileyChris I took care of the template

**Comment by sodevious** [comment]
![rapidpro health style guide 2](https://user-images.githubusercontent.com/915966/38052570-af6a1aa6-329f-11e8-983c-5b9ebe608671.png)

**Comment by mtrythall** [comment]
Closing the ticket, but would like to see Style moved to after the Body field.
