### ISSUE TITLE
Responsive Image Plugin

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#43]
The current Image plugin is not responsive. We need access to the HTML so we can use Foundation's responsive code via Interchange. We also need to be aware of placeholders so we don't load inappropriately sized images.

So, we need a HTML file to reference to begin work.

**Comment by SmileyChris** [comment]
I need to know more details about what is actually wanted here. Are *all* images to be responsive? How many responsive sizes are we after? Can I have some example interchange code to work with?
