### ISSUE TITLE
404 + 500 Pages

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#47]
We need some help 404 and 500 pages.

**Comment by mtrythall** [comment]
Yup, I think @SmileyChris needs to do something. Forgot/Can't remember if we need special views. Passing to him.

**Comment by SmileyChris** [comment]
The templates are rendered when debug mode is off.
You can test in a development enviroment with two new urls I added: `/404/` and `/500/`.

There was an issue with rendering with sekizai_tags on the 500 page (it uses an empty context), but it didn't look like we were actually using this functionality so I just switched it back to a standard django `{% block %}` tag for the js and css blocks.
