### ISSUE TITLE
Form Styles

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#52]
We should have form styles:

https://invis.io/NXGS1KNBASW

**Comment by sodevious** [comment]
@mtrythall do you know how we are intending to implement the contact form in the backend? id like to make sure the designs there are correct before considering this card complete

**Comment by mtrythall** [comment]
@sodevious No, we're still locking that down. Right now I have:

> Fields: Name, Institution, Country, Email, Project scope, Message

So, text, text, drop down, email, drop down, textarea. For your purposes, it'll just be HTML, nothing else fancy.

**Comment by mtrythall** [comment]
It'll post to a generic view, probably, that sends a text-only email.

**Comment by sodevious** [comment]
@mtrythall only some are required, so im just adding an asterisk to the label how it's presented in the mock
