### ISSUE TITLE
Refactor .subpage-hero

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#58]
Details TBD

**Comment by mtrythall** [comment]
This one seems super fragile and an abuse of Hero. It also doesn't work well on mobile, text isn't aligned at the bottom of the background as it is on the comps.

@sodevious can you rebuild/clean this up?

<img width="1017" alt="screenshot 2018-04-13 14 39 34" src="https://user-images.githubusercontent.com/84750/38752237-7d1f7510-3f28-11e8-96cd-9a35a92f507b.png">

<img width="986" alt="screenshot 2018-04-13 14 40 04" src="https://user-images.githubusercontent.com/84750/38752265-8f933d08-3f28-11e8-9d5b-e5cc68fd0dbf.png">

**Comment by sodevious** [comment]
@mtrythall  When you say "This one seems super fragile and an abuse of Hero", does that mean you want it refactored without using `.hero`?

**Comment by mtrythall** [comment]
What I'm suggesting is that hero has too many variations. We're making a single class do too much work.

**Comment by mtrythall** [comment]
Going to file a separate issue for the second scenario. On mobile, we want the background to sort of cut off, with the image sticking out, on mobile. This works for now, looks good 👍 and is a lot cleaner. I'm impressed!
