### ISSUE TITLE
Card Grid > Photo Card: All Tags and CTAs should line up

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#60]
<img width="801" alt="screenshot 2018-04-11 22 08 06" src="https://user-images.githubusercontent.com/84750/38652637-ded5900a-3dd4-11e8-9338-14ba481bd6c6.png">

**Comment by sodevious** [comment]
@mtrythall how do you feel about a text ellipsis as part of the solution? (example in first card)
<img width="752" alt="screenshot 2018-04-13 12 36 36" src="https://user-images.githubusercontent.com/915966/38746996-5edf9438-3f17-11e8-919f-faf97b213137.png">
