### ISSUE TITLE
Footer should be fixed to the bottom

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#79]
On short pages (of which there will be few), the footer is high up. It should always be fixed to the bottom.

Careful to respect the off-canvas nav when making this change.

<img width="1195" alt="screenshot 2018-04-24 16 22 52" src="https://user-images.githubusercontent.com/84750/39212126-c7042b9c-47db-11e8-979f-1b6c09e9968e.png">

**Comment by mtrythall** [comment]
Almost there. Have a gap at the bottom of the site now.

<img width="359" alt="screenshot 2018-04-27 22 59 52" src="https://user-images.githubusercontent.com/84750/39391263-bb4bb316-4a6e-11e8-9ca9-9a759275e42d.png">

**Comment by mtrythall** [comment]
Can you take a look please?

**Comment by sodevious** [comment]
@mtrythall what browser is this?

**Comment by sodevious** [comment]
* Also this breaks in IE 11

**Comment by mtrythall** [comment]
Still seeing this one. Any luck on your end?

**Comment by sodevious** [comment]
@mtrythall I actually haven't seen it at all yet :cry:

**Comment by sodevious** [comment]
Was hoping I'd come across it while developing and working on some of these other bugs. Will have to take another stab at testing to find it.

**Comment by mtrythall** [comment]
Ok. Yeah, I see it on Safari too. I can take a look this weekend too. I just didn't see *any* element that would be causing it. Everything checked out!

**Comment by mtrythall** [comment]
I can't reproduce this on crossbrowsertesting.com, so, marking it closed.
