### ISSUE TITLE
Need inline link colors

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#85]
They're using the default blue from Foundation. Perhaps Navy?

Example: https://unicef-rapidpro-for-health.herokuapp.com/functions/

![screenshot 2018-04-24 22 35 57](https://user-images.githubusercontent.com/84750/39223391-ddd39130-480f-11e8-9d1e-341c15fb8f50.png)

**Comment by mtrythall** [comment]
@russelq Any thoughts on this?

**Comment by mtrythall** [comment]
Sorry, should say, we're going with the Navy color. Any issues there?

**Comment by mtrythall** [comment]
Here's how Navy looks

<img width="776" alt="screenshot 2018-04-26 12 09 28" src="https://user-images.githubusercontent.com/84750/39317884-b21f7c16-494a-11e8-8cac-b6af5e5d874e.png">

Links don't jump out. Maybe a thicker border, different color?

**Comment by sodevious** [comment]
Here's light navy
<img width="954" alt="screenshot 2018-04-26 12 11 43" src="https://user-images.githubusercontent.com/915966/39318029-043360b2-494b-11e8-9159-bf45b7d25ef9.png">

**Comment by sodevious** [comment]
And with a border that stands out a little more
<img width="953" alt="screenshot 2018-04-26 12 13 20" src="https://user-images.githubusercontent.com/915966/39318113-409c0694-494b-11e8-949f-608ac63456fb.png">

**Comment by russelq** [comment]
I like bottom-border more than text-underline

**Comment by mtrythall** [comment]
Let's go with border-bottom and play with the weight of it. 2px? 3px?

Not sure about the light, seems inactive/visited.

**Comment by russelq** [comment]
Good point on the light color. 

This is sort of my go-to approach with text links, but I like to use border-bottom, with a 1px (or 2px) weight and dotted-line. If you use the dark navy color with that approach, the line should be prominent but still somewhat subtle.

**Comment by sodevious** [comment]
how's this?
<img width="955" alt="screenshot 2018-04-26 14 27 58" src="https://user-images.githubusercontent.com/915966/39324661-0baf1d0a-495e-11e8-88a9-54a7cf1447ba.png">

**Comment by mtrythall** [comment]
Colors look good. I made the border disappear on hover, but there's a flicker. Need to address.
