### ISSUE TITLE
margin for pictures into subpage w/Sidebar template

### ISSUE THREAD

**Issue by vturmine** [rapidpro/chpro-microsite#86]
@mtrythall - in use case, when we add a picture as one element of the main content, picture needs a bottom margin with the next element. I let you an example with vaccination.

**Comment by mtrythall** [comment]
Oh, darn. I thought we covered this, but I realize we changed the HTML last minute. Thanks for catching. We'll address!

@sodevious We may want to wrap these sort of images in a `<figure>` tag, but the file we're using isn't for figures as much as it is for *all* inline images. Can you make a call and tackle?

**Comment by sodevious** [comment]
@mtrythall this approach may be too simplified, but would appreciate your thoughts
