### ISSUE TITLE
Footer logo isn't left aligned on desktop in Safari

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#98]
<img width="358" alt="screenshot 2018-05-04 00 02 31" src="https://user-images.githubusercontent.com/84750/39612553-873cebf2-4f2e-11e8-9893-7c89c07fa455.png">

**Comment by sodevious** [comment]
@mtrythall Not seeing this in FF, Safari or Chrome. 
![screenshot 2018-05-28 21 06 47](https://user-images.githubusercontent.com/915966/40626795-3f09f6f4-62bb-11e8-889f-ed431e488b7c.png)

**Comment by sodevious** [comment]
Closing because now moot due to #101
